import { useState, useEffect } from "react";
import {
  LiveKitRoom,
  VideoConference,
  useRoomContext,
} from "@livekit/components-react";
import { RoomEvent } from "livekit-client";
import "@livekit/components-styles";
import "./App.css";

const SERVER_URL = "ws://localhost:7880";

// Paste your JWT token generated by token.js here
const TOKEN =
  "eyJhbGciOiJIUzI1NiJ9.eyJ2aWRlbyI6eyJyb29tSm9pbiI6dHJ1ZSwicm9vbSI6InRlc3Qtcm9vbSIsImNhblB1Ymxpc2giOnRydWUsImNhblN1YnNjcmliZSI6dHJ1ZX0sImlzcyI6ImRldmtleSIsImV4cCI6MTc3ODYwMDQxMCwibmJmIjoxNzc4NTE0MDEwLCJzdWIiOiJuaXZldGhhIn0.HuRlW7MYLjj9so7okjONCtyzczoHuUgfKgKgjMXDoIc";

function LiveCaptions() {
  const room = useRoomContext();
  const [captions, setCaptions] = useState([]);

  useEffect(() => {
    const handleTranscription = (segments, participant) => {
      const finalSegments = segments.filter((s) => s.final);
      if (finalSegments.length === 0) return;

      finalSegments.forEach((segment) => {
        const caption = {
          id: segment.id,
          text: segment.text,
          speaker: participant?.identity || "Speaker",
        };

        setCaptions((prev) => [...prev.slice(-2), caption]);

        setTimeout(() => {
          setCaptions((prev) => prev.filter((c) => c.id !== segment.id));
        }, 6000);
      });
    };

    room.on(RoomEvent.TranscriptionReceived, handleTranscription);
    return () => room.off(RoomEvent.TranscriptionReceived, handleTranscription);
  }, [room]);

  if (captions.length === 0) return null;

  return (
    <div className="captions-overlay">
      {captions.map((c) => (
        <div key={c.id} className="caption-line">
          <span className="caption-speaker">{c.speaker}:</span>
          <span className="caption-text">{c.text}</span>
        </div>
      ))}
    </div>
  );
}

export default function App() {
  return (
    <div className="app-shell">
      <LiveKitRoom
        serverUrl={SERVER_URL}
        token={TOKEN}
        connect={true}
        audio={true}
        video={true}
      >
        <div className="room-container">
          <VideoConference />
          <LiveCaptions />
        </div>
      </LiveKitRoom>
    </div>
  );
}
